### ISSUE TITLE
Latest version 5.0 not working on Win 10

### ISSUE THREAD

**Issue by kraith** [marcelstoer/nodemcu-pyflasher#90] opened 2022-02-26 12:54 UTC
Using Win 10 64bit build 19044
When clicking the exe nothing happens, no pop-up. no errors,
With previous build 4.0 and below are works fine

**Comment by marcelstoer** [comment] 2022-02-26 14:02
Duplicate of #78

**Closed by marcelstoer** 2022-02-26 14:02 UTC
