### ISSUE TITLE
Is it actually erasing the whole flash mem in 2 seconds?

### ISSUE THREAD

**Issue by tombot52-github** [marcelstoer/nodemcu-pyflasher#14] opened 2017-04-23 19:46 UTC
I'm programming a ESP-12E on a Win7 computer.
Your new Pyflasher V1.0.1 program looks like it might be easier to use than the
original NodeMCU Flasher - for windows computers.
But although it says that it has successfully flashed the memory, I have yet to 
get any of the binaries I've flashed with it, to boot.

Here's the log it produces:

Connecting....
Running Cesanta flasher stub...
Erasing flash (this may take a while)...
Erase took 1.6 seconds
Connecting....
Auto-detected Flash size: 32m
Running Cesanta flasher stub...
Flash params set to 0x0040
Writing 450560 @ 0x0... 
Wrote 450560 bytes at 0x0 in 39.2 seconds (91.9 kbit/s)...
Leaving...
Verifying just-written flash...
Flash params set to 0x0040
Verifying 0x6de18 (450072) bytes @ 0x00000000 in flash against D:\Downloads\ESP8266\Software\Firmware\V0.9.6\nodemcu_integer_0.9.6-dev_20150704.bin...
-- verify OK (digest matched)

Notice how it says it took only 1.6 seconds to erase the memory.
And that's true - that function skips through in only 2 seconds.

In the past I've only gotten my unit to boot after having FIRST flashed the full memory with so called "blank" files.
That is, those that have been programmed with FF in each byte of the 1MB section on memory.
So the 0x00000, 0x10000, 0x20000, and 0x30000 address sections all get set to FF in every byte.
In all of those cases it took at least 10 minutes to erase the 4MB of memory.
The binaries I've been trying to flash have not only been from the NodeMCU Custom Builds website, but the 0.9.6 version as well.

I've only been at this for 3 weeks, and it's been a pretty steep learning curve, so please forgive any 
newbie assumptions I might make.
Regardless of if I select erase flash, or not, I haven't yet seen success with this version of this tool.
Although I do appreciate the effort.

**Comment by marcelstoer** [comment] 2017-04-23 20:00
> Your new Pyflasher V1.0.1 program looks like it might be easier to use than the
original NodeMCU Flasher - for windows computers.

It is and in contrast to the other one it _is_ still maintained.

> D:\Downloads\ESP8266\Software\Firmware\V0.9.6\nodemcu_integer_0.9.6-dev_20150704.bin

There's the culprit. Those 0.9.x binaries are hopelessly outdated. [Build](https://nodemcu.readthedocs.io/en/latest/en/build/) a recent firmware and connect to it after flashing with [ESPlorer et.al.](https://nodemcu.readthedocs.io/en/latest/en/upload/) at 115'200 bps.

> Notice how it says it took only 1.6 seconds to erase the memory.

Sounds about right. I believe the underlying esptool.py program quick-"erases" the memory like what was done in the past with hard disk drives. Rather than safe-erasing (that's what you did by writing 0s to every sector) all sectors are simply marked as free - or something like this.

> the NodeMCU Custom Builds website.

That's from yours truly as well 😉 

> I haven't yet seen success with this version of this tool.

Over 2000 installations w/o any issues suggest the problem is not with the tool but with something else.

**Closed** 2017-05-06 14:49 UTC
